
version: 2.1
jobs:
  build:
    working_directory: ~/Woodsman
    docker:
      # running an image of android 10
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          # give circleci permission to run files
          name: CHMOD permissions
          command: chmod +x ./gradlew
      - run:
          # make sure the project builds
          name: Build Project
          command: ./gradlew build
