
version: 2.1
jobs:
  build:
    working_directory: ~/Woodsman
    docker:
      # running an image of android 10
      - image: circleci/android:api-29
    steps:
      - checkout
      # load project dependencies from cache
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          # give circleci permission to run files
          name: CHMOD permissions
          command: chmod +x ./gradlew
      - run:
          # make sure the project builds
          name: Build Project
          command: ./gradlew build
      # save updated cache
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}