
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/Woodsman
    docker:
    # running an image of android 10
      - image: circleci/android:api-29
    steps:
      - checkout
    # load project dependencies from cache
    # https://circleci.com/docs/2.0/caching/
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          # give circleci permission to run files
          name: CHMOD permissions
          command: chmod +x ./gradlew
      - run:
          # Export base64 encoded google-services.json
          # into local bash variables
          name: Export Google Services Json
          command: echo 'export GOOGLE_SERVICES_JSON="$GOOGLE_SERVICES_JSON"' >> $BASH_ENV
      - run:
          # Decode the base64 string
          name: Decode Google Services Json
          command: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json
      - run:
          # run detekt to check for code smell and static analysis
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          # run ktlint to check kotlin code for kotlin standards
          name: Run Ktlint
          command: ./gradlew ktlint
      - run:
          # run lint to check all code fits code standards
          name: Run Lint
          command: ./gradlew lintDevDebug
      - run:
          # run spotless to format kotlin code
          name: Run Spotless
          command: ./gradlew spotlessKotlinCheck
      - run:
          # run all unit tests
          name: Run Unit Tests
          command: ./gradlew testDevDebugUnitTest
      - run:
          # run jacoco to generate code coverage
          name: Generate Code Coverage
          command: ./gradlew jacocoTestReportDevDebug
      #- run:
          # make sure the project builds
          #name: Build Project
          #command: ./gradlew build
      - codecov/upload:
          # Upload coverage to codecov
          flags: unittest
          conf: .codecov/config.yml
    # save updated cache
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
